name: Build and Test Testudo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
# The crate ark-ff uses the macro llvm_asm! when emitting asm which returns an
# error because it was deprecated in favour of asm!. We temporarily overcome
# this problem by setting the environment variable below (until the crate
# is updated).
env:
  RUSTFLAGS: "--emit asm -C llvm-args=-x86-asm-syntax=intel"

jobs:
  build_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: rustup default nightly
      - name: Install rustfmt Components
        run: rustup component add rustfmt
      # - name: Install clippy
      #   run: rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build examples
        run: cargo build --examples --verbose
      - name: Check Rustfmt Code Style
        run: cargo fmt --all -- --check
      # cargo clippy uses cargo check which returns an error when asm is emitted
      # we want to emit asm for ark-ff operations so we avoid using clippy for # now
      # - name: Check clippy warnings
      #   run: cargo clippy --all-targets --all-features
