name: Build and Test Testudo

on: [push, pull_request]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true

      - name: cargo test
        run: RUST_LOG=info cargo test --all --all-features -- --nocapture