name: Build and Test Testudo

on:
  push:
    branches:
      - main
  pull_request:

name: Test

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true

      - name: cargo test
        working-directory: node
        run: RUST_LOG=info cargo test --all --all-features -- --nocapture